#!/bin/bash
# =============================================================================
# ADD NODE TO MESH - One-Click Script
# =============================================================================
# Thêm VPS mới vào WireGuard mesh chỉ với 1 lệnh
#
# Usage:
#   ./scripts/add-node.sh <node_name> <public_ip> <wg_ip> [ssh_port]
#
# Examples:
#   ./scripts/add-node.sh db-primary 155.133.7.195 10.10.0.10 2222
#   ./scripts/add-node.sh app-server 1.2.3.4 10.10.0.20
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Hub configuration
HUB_PUBLIC_KEY="9c7Sd43PyenG33LjKho0TKykNCJbqgXwhJHRF0jloEs="
HUB_ENDPOINT="5.104.82.252"
HUB_WG_IP="10.10.0.1"

print_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════════════════════════════════╗"
    echo "║         🚀 ONE-CLICK ADD NODE TO WIREGUARD MESH                      ║"
    echo "╚══════════════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }
print_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }

# Check arguments
if [ $# -lt 3 ]; then
    print_banner
    echo "Usage: $0 <node_name> <public_ip> <wg_ip> [ssh_port]"
    echo ""
    echo "Examples:"
    echo "  $0 db-primary 155.133.7.195 10.10.0.10 2222"
    echo "  $0 app-server 1.2.3.4 10.10.0.20"
    echo ""
    echo "IP Ranges:"
    echo "  10.10.0.10-19  - Database nodes"
    echo "  10.10.0.20-29  - Application nodes"
    echo "  10.10.0.30-39  - Monitoring nodes"
    exit 1
fi

NODE_NAME="$1"
PUBLIC_IP="$2"
WG_IP="$3"
SSH_PORT="${4:-22}"

print_banner
echo "Node Name:     $NODE_NAME"
echo "Public IP:     $PUBLIC_IP"
echo "WireGuard IP:  $WG_IP"
echo "SSH Port:      $SSH_PORT"
echo ""

# =============================================================================
# STEP 1: Test SSH connectivity
# =============================================================================
print_info "Step 1/5: Testing SSH connectivity..."

if ! nc -zw3 "$PUBLIC_IP" "$SSH_PORT" 2>/dev/null; then
    print_error "Cannot connect to $PUBLIC_IP:$SSH_PORT"
    print_info "Make sure SSH is running and port is open"
    exit 1
fi
print_success "SSH port $SSH_PORT is open"

# =============================================================================
# STEP 2: Copy SSH key if needed
# =============================================================================
print_info "Step 2/5: Setting up SSH key..."

if ! ssh -p "$SSH_PORT" -o BatchMode=yes -o ConnectTimeout=5 root@"$PUBLIC_IP" 'echo ok' &>/dev/null; then
    print_warning "SSH key not configured, copying..."
    ssh-copy-id -p "$SSH_PORT" -o StrictHostKeyChecking=no root@"$PUBLIC_IP"
fi
print_success "SSH key configured"

# =============================================================================
# STEP 3: Install WireGuard on remote node
# =============================================================================
print_info "Step 3/5: Installing WireGuard on remote node..."

ssh -p "$SSH_PORT" root@"$PUBLIC_IP" bash << REMOTE_SCRIPT
set -e
# Install WireGuard
apt-get update -qq
apt-get install -y -qq wireguard wireguard-tools

# Enable IP forwarding
echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/99-wireguard.conf
sysctl -p /etc/sysctl.d/99-wireguard.conf > /dev/null

# Create directory
mkdir -p /etc/wireguard
chmod 700 /etc/wireguard

# Generate keys if not exist
if [ ! -f /etc/wireguard/private.key ]; then
    wg genkey | tee /etc/wireguard/private.key | wg pubkey > /etc/wireguard/public.key
    chmod 600 /etc/wireguard/private.key
fi

# Get keys
PRIVATE_KEY=\$(cat /etc/wireguard/private.key)

# Create config
cat > /etc/wireguard/wg0.conf << EOF
# $NODE_NAME - Generated by add-node.sh
[Interface]
PrivateKey = \$PRIVATE_KEY
Address = $WG_IP/24

[Peer]
# Hub Server
PublicKey = $HUB_PUBLIC_KEY
Endpoint = $HUB_ENDPOINT:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
EOF

# Start WireGuard
systemctl enable wg-quick@wg0 2>/dev/null || true
systemctl restart wg-quick@wg0

echo "WIREGUARD_INSTALLED"
REMOTE_SCRIPT

print_success "WireGuard installed on $NODE_NAME"

# =============================================================================
# STEP 4: Get public key and add to Hub
# =============================================================================
print_info "Step 4/5: Adding peer to Hub..."

NODE_PUBKEY=$(ssh -p "$SSH_PORT" root@"$PUBLIC_IP" 'cat /etc/wireguard/public.key')

# Check if peer already exists
if grep -q "$NODE_PUBKEY" /etc/wireguard/wg0.conf 2>/dev/null; then
    print_warning "Peer already exists in Hub config"
else
    # Add peer to Hub config
    cat >> /etc/wireguard/wg0.conf << EOF

[Peer]
# $NODE_NAME
PublicKey = $NODE_PUBKEY
AllowedIPs = $WG_IP/32
EOF
    
    # Reload WireGuard
    wg syncconf wg0 <(wg-quick strip wg0)
    print_success "Peer added to Hub"
fi

# =============================================================================
# STEP 5: Verify connectivity
# =============================================================================
print_info "Step 5/5: Verifying connectivity..."
sleep 2

if ping -c 2 -W 3 "$WG_IP" &>/dev/null; then
    PING_STATUS="✅ CONNECTED"
else
    PING_STATUS="⏳ Establishing..."
    sleep 3
    if ping -c 2 -W 3 "$WG_IP" &>/dev/null; then
        PING_STATUS="✅ CONNECTED"
    else
        PING_STATUS="❌ Failed (check firewall)"
    fi
fi

# =============================================================================
# FINAL: Display results
# =============================================================================
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              ✅ NODE ADDED TO MESH!                                          ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  Node Name:     $NODE_NAME${NC}"
echo -e "${GREEN}║  Public IP:     $PUBLIC_IP${NC}"
echo -e "${GREEN}║  WireGuard IP:  $WG_IP${NC}"
echo -e "${GREEN}║  Public Key:    $NODE_PUBKEY${NC}"
echo -e "${GREEN}║  Status:        $PING_STATUS${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════════════════════╝${NC}"

# Show current mesh status
echo ""
print_info "Current WireGuard Mesh:"
wg show wg0 | grep -E "peer|endpoint|latest handshake|allowed ips"
